// layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import Footer from "./components/Footer";
import ConditionalHeader from "./components/ConditionalHeader";
import ConditionalFooter from "./components/ConditionalFooter";
import { CartProvider } from "@/context/CartContext"; // Make sure the path is correct

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
       
        <CartProvider>
        <ConditionalHeader />
          <main className="flex-grow">{children}</main>
          <ConditionalFooter />
        </CartProvider>
        
      </body>
    </html>
  );
}
